stages:
  - deploy
deploy:
  stage: deploy
  image: docker:19.03.12
  only:
  - main
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export COMMIT_TIME=$(date +%s)
    - docker build . -f Dockerfile -t $CI_REGISTRY_IMAGE:$COMMIT_TIME
    - docker push $CI_REGISTRY_IMAGE:$COMMIT_TIME
