apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ubl-tracker
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: python-ubl-tracker
      app.kubernetes.io/name: python-ubl-tracker