apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ubl-tracker
  labels:
    monitoring: thinkbox
    release: monitoring-kube-prometheus-stack
spec:
  endpoints:
  - port: http
    interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/instance: python-ubl-tracker
      app.kubernetes.io/name: python-ubl-tracker