apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-ubl-tracker.fullname" . }}
  labels:
    monitoring: thinkbox
    release: monitoring-kube-prometheus-stack
    {{- include "python-ubl-tracker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "python-ubl-tracker.selectorLabels" . | nindent 4 }}
